apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - pdb.yaml
  - ingress-route.yaml
  - middlewares.yaml

labels:
  - pairs:
      managed-by: kustomize
    includeSelectors: false
