apiVersion: v1
kind: Service
metadata:
  name: cervical-ai-viewer
  labels:
    app: cervical-ai-viewer
spec:
  selector:
    app: cervical-ai-viewer
  ports:
    - port: 80
      targetPort: 8000
      name: http
  type: ClusterIP
