apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    environment: staging
    # Optional: clarifies that the platform repo created it
    argocd.argoproj.io/managed-by: argocd
  annotations:
    # <-- This is the key line -->
    argocd.argoproj.io/sync-options: Prune=false
