apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicHJhZHkwdCIsInBhc3N3b3JkIjoiZ2hwX0tUNVMyODJFaUc4a0Zna0t2RzFyR2RIa2M1TjlVSTFkdUFReiIsImVtYWlsIjoiOTkyMTY5NTYrcHJhZHlvdFJhbmphbkB1c2Vycy5ub3JlcGx5LmdpdGh1Yi5jb20iLCJhdXRoIjoiY0hKaFpIa3dkRHBuYUhCZlMxUTFVekk0TWtWcFJ6aHJSbWRyUzNaSE1YSkhaRWhyWXpWT09WVkpNV1IxUVZGNiJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
