# Run this command to create the secret
#  kubectl create secret docker-registry ghcr-secret \              ─╯
#   --docker-server=ghcr.io \
#   --docker-username=prady0t \
#   --docker-password=PAT TOKEN\
#   --docker-email=dummy@example.com
