# mlflow/oauth2-proxy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: mlflow
spec:
  replicas: 2
  selector:
    matchLabels: { app: oauth2-proxy }
  template:
    metadata:
      labels: { app: oauth2-proxy }
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
        args:
        - --provider=google
        - --redirect-url=https://mlflow.cervical-screening.pythonaisolutions.com/oauth2/callback
        - --upstream=http://mlflow.mlflow.svc.cluster.local
        - --http-address=0.0.0.0:4180
        - --cookie-secure=true
        - --cookie-refresh=1h
        - --set-authorization-header=true
        - --pass-access-token=true
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --skip-provider-button=true
        # - --skip-jwt-bearer-tokens=true
        - --extra-jwt-issuers=https://accounts.google.com=$(DESKTOP_CLIENT_ID)
        - --email-domain=pythonaisolutions.com
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom: { secretKeyRef: { name: oauth2-proxy-secret, key: client_id } }
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom: { secretKeyRef: { name: oauth2-proxy-secret, key: client_secret } }
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom: { secretKeyRef: { name: oauth2-proxy-secret, key: cookie_secret } }
        - name: DESKTOP_CLIENT_ID
          valueFrom: { secretKeyRef: { name: oauth2-proxy-secret, key: desktop_client_id } }
        ports:
        - containerPort: 4180
          name: http
        readinessProbe:
          httpGet: { path: /ping, port: 4180 }
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /ping, port: 4180 }
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: mlflow
spec:
  selector: { app: oauth2-proxy }
  ports:
  - name: http
    port: 80
    targetPort: 4180
